/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangSectionIndexRouteImport } from './routes/$lang/$section/index'

const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSectionIndexRoute = LangSectionIndexRouteImport.update({
  id: '/$lang/$section/',
  path: '/$lang/$section/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$lang/': typeof LangIndexRoute
  '/$lang/$section/': typeof LangSectionIndexRoute
}
export interface FileRoutesByTo {
  '/$lang': typeof LangIndexRoute
  '/$lang/$section': typeof LangSectionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$lang/': typeof LangIndexRoute
  '/$lang/$section/': typeof LangSectionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$lang/' | '/$lang/$section/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$lang' | '/$lang/$section'
  id: '__root__' | '/$lang/' | '/$lang/$section/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
  LangSectionIndexRoute: typeof LangSectionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/$section/': {
      id: '/$lang/$section/'
      path: '/$lang/$section'
      fullPath: '/$lang/$section/'
      preLoaderRoute: typeof LangSectionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LangIndexRoute: LangIndexRoute,
  LangSectionIndexRoute: LangSectionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
